= Classpath to File Gradle Plugin
:pluginId: com.redock.classpathtofile
:pluginVersion: 0.0.1
:toc: macro

toc::[]

== Overview

When the classpath for a Gradle `JavaExec` or `Test` task is long, Windows command executions
fail due to Windows path length limitations. The error usually seen in this case is
`CreateProcess error=206, The filename or extension is too long`.

This plugin uses the capability of JDK9+ to pass the classpath to the JVM in an "argument file"
instead (see https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-4856361B-8BFD-4964-AE84-121F5F6CF111[java
Command-Line Argument Files]), thus avoiding the OS limitation.

In addition, this avoids modifying classloading or any other runtime behavior, which is not the
case with other solutions such as ones that modify the classpath in the manifest. See:

* https://github.com/viswaramamoorthy/gradle-util-plugins
* https://github.com/virgo47/gradle-classpath-jar-plugin

This plugin takes inspiration from those plugins, but operates in a completely different way.

See this answer to
https://stackoverflow.com/questions/201816/how-to-set-a-long-java-classpath-in-windows/54270831#54270831[How
to set a long Java classpath in Windows?] at StackOverflow for more details about this solution.

See this upstream Gradle issue about potentially providing a solution to this problem in
Gradle core: https://github.com/gradle/gradle/issues/1989. Hopefully an upstream solution to
this will eliminate the need for this plugin.

== Notes on Modularity

This plugin tries to detect if the current project is modularized.
If it is, the `module-path` is adapted instead of the class path.
Since the classpath variable of gradle is cleared after the patch, plugins relying on it stop working.
As a consequence, this plugin cannot be used together with https://github.com/java9-modularity/gradle-modules-plugin[org.javamodularity.moduleplugin].

== Version Compatibility

* Gradle 8.8+ (may work on earlier versions, but untested)
* Java 8+.

⚠ Works only if https://docs.gradle.org/current/userguide/configuration_cache.html[configuration caching] is disabled ⚠

== Installation

Simply add:

```groovy
plugins {
  id 'com.redock.classpathtofile' version '0.1.0'
}
```

to your build.

For more details, follow the steps described at the
https://plugins.gradle.org/plugin/com.redock.classpathtofile[Gradle Plugin Portal page].
